global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: '<monitor-name>'

rule_files:
  - 'recording.rules.yml'

scrape_configs:
  - job_name: reverse-proxy-poc
    metrics_path: /api/4489233/metrics
    static_configs:
      - targets: ['api.blockeden.xyz']

  - job_name: 'sui-validator'
    static_configs:
      - targets: ['34.168.101.125:9184']
